### ISSUE TITLE
the traffic I get on google map since 2020-05-31 is zero

### ISSUE THREAD

**Issue by pschaus** [Jigsaw-Code/net-analysis#10]
I didn't dig to see the reason of the problem but everything looks fine on https://transparencyreport.google.com/traffic

**Comment by cjhenck** [comment]
@ohnorobo do you know anything about this?

**Comment by ohnorobo** [comment]
At https://transparencyreport.google.com/traffic/overview?lu=fraction_traffic I currently don't see any data for any product/region after 2020-06-04. I would bet there are pipeline issues and the failures are related.

**Comment by ohnorobo** [comment]
Ran a fresh data download and got files with 0 data starting at 2020-06-04T07:30, which matches the missing data I see on the traffic report page. @pschaus I bet the 2020-05-31 data was missing when you ran your download, but has since been backfilled.

I'll update this bug when the currently missing data is backfilled as well.

**Comment by ohnorobo** [comment]
I forgot to update this bug, sorry! This issue has been fixed since July 6th.
